### PR TITLE
fix for usage with cocoapods 'use_frameworks!'

### PR DESCRIPTION
**Pull request by adrian-gierakowski**
making user module can be found when NODE_ is used as framework 

see also: https://github.com/adrian-gierakowski/NODE/commit/6d69ce3d81f6227b974da9cdf4255a25a58f3e4a

### CODE REVIEW

**Comment by adrian-gierakowski** [comment]
@ross: it failed again, this time during pod install, I have cleared cache and restarted the test run

**Comment by ross** [comment]
> @ross: it failed again, this time during pod install, I have cleared cache and restarted the test run

Probably not the Ross you're looking for :-)

**Comment by adrian-gierakowski** [comment]
@ross: sorry, wrong repo, wrong pull request  :)

**Comment by markohlebar** [comment]
@adrian-gierakowski yeah that looks good, thanks!

**Comment by adrian-gierakowski** [comment]
@markohlebar : cool! I created a similar pull request in the NODE repository ( as linked above )

**Pull request merged**
